"""create soil analyses table

Revision ID: 00ef09b0df65
Revises: 4524834a373b
Create Date: 2026-07-25 23:48:17.999553

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "00ef09b0df65"
down_revision: Union[str, Sequence[str], None] = "4524834a373b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "soil_analyses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("analysis_date", sa.Date(), nullable=False),
        sa.Column("ph", sa.Float(), nullable=False),
        sa.Column("nitrogen", sa.Float(), nullable=False),
        sa.Column("phosphorus", sa.Float(), nullable=False),
        sa.Column("potassium", sa.Float(), nullable=False),
        sa.Column("organic_matter", sa.Float(), nullable=False),
        sa.Column("moisture", sa.Float(), nullable=False),
        sa.Column("laboratory", sa.String(length=150), nullable=False),
        sa.Column("recommendations", sa.String(length=1000), nullable=True),
        sa.Column("field_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["field_id"],
            ["fields.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("soil_analyses")
    # ### end Alembic commands ###
