"""add growth_stage to crops

Revision ID: 16c8e7634aac
Revises: f83c8c608295
Create Date: 2026-07-28 09:39:10.684220

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "16c8e7634aac"
down_revision: Union[str, Sequence[str], None] = "f83c8c608295"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "crops",
        sa.Column(
            "growth_stage",
            sa.String(length=50),
            nullable=False,
            server_default="VEGETATIVE",
        ),
    )

    op.create_index(op.f("ix_fields_farm_id"), "fields", ["farm_id"], unique=False)
    op.create_index(op.f("ix_weather_field_id"), "weather", ["field_id"], unique=False)
    op.create_index(
        op.f("ix_weather_forecast_date"),
        "weather",
        ["forecast_date"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_weather_forecast_date"), table_name="weather")
    op.drop_index(op.f("ix_weather_field_id"), table_name="weather")
    op.drop_index(op.f("ix_fields_farm_id"), table_name="fields")
    op.drop_column("crops", "growth_stage")
    # ### end Alembic commands ###
