"""create weather table

Revision ID: f83c8c608295
Revises: eaf21fc073bf
Create Date: 2026-07-26 13:08:58.678509

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f83c8c608295"
down_revision: Union[str, Sequence[str], None] = "eaf21fc073bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("weather", sa.Column("source", sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("weather", "source")
    # ### end Alembic commands ###
